- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8081 pratibha012/financeme:1.0
      args:
        warn: false

